[package]
name = "tendril"
version = "1.0.10"
authors = ["taylor <taylor@teukka.tech>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
build = { path = "../libs/build" }
futures = "0.3.21"
lazy_static = "1.4.0"
wikitext = { path = "../libs/wikitext" }
persistance = { path = "../libs/persistance" }
render = { path = "../libs/render" }
regex = "1.5.5"
search_engine = { path = "../libs/search-engine" }
task_runners = { path = "../libs/task-runners" }
tokio = { version = "1.17.0", features = ["fs", "macros", "rt-multi-thread"], default-features = false }
www = { path = "../libs/www" }

[workspace]
resolver = "2"
